# Generated by Django 3.2.7 on 2021-09-27 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houm', '0002_auto_20210927_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='dateModified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
