# Generated by Django 3.2.7 on 2021-09-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houm', '0005_auto_20210928_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='visited',
        ),
        migrations.AddField(
            model_name='position',
            name='visit_duration',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='position',
            name='distance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='position',
            name='speed',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
    ]
